POST http://localhost:3000/api/v1/admin/user/new
Content-Type: application/json

{
  "userId": "user",
  "pwd": "pwd",
  "branchName": "branchName",
  "branchManager": "branchManager",
  "branchContact": "branchContact"
}

###
GET http://localhost:3000/api/v1/admin/tx/list
Accept: application/json

###
POST http://localhost:3000/api/v1/admin/user/group/1/product/add
Content-Type: application/json

{
  "products": [
    {
      "id": 1,
      "productName": "product1"
    },
    {
      "id": 2,
      "productName": "product2"
    }
  ]
}

###
GET http://localhost:3000/api/v1/admin/user/group/1
Accept: application/json

###
GET http://localhost:3000/api/v1/admin/user/group/list
Accept: application/json

###
GET http://localhost:3000/api/v1/admin/user/list
Accept: application/json

###
POST http://localhost:3000/api/v1/admin/user/group/new
Content-Type: application/json

{
  "groupName": "group1",
  "description": "group1 description"
}

###
POST http://localhost:3000/api/v1/admin/product/new
Content-Type: application/json

{
  "productName": "product3",
  "productPrice": 50000.12,
  "description": "product3 description"
}

###
GET http://localhost:3000/api/v1/admin/auth/list
Accept: application/json

###
POST http://localhost:3000/api/v1/admin/auth/new
Content-Type: application/json

{
  "userId": "admin",
  "pwd": "admin",
  "name": "admin"
}

###
